### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by atmangel** [square/connect-php-sdk#106]
Hi, please i need example to charge a credit card (credit card number, expiry and cvv) and create the customer (email, address, city, etc.), thanks

**Comment by havenwood** [comment]
I'd suggest going through the first half of the [Payment Form Walkthrough](https://developer.squareup.com/docs/payment-form/payment-form-walkthrough), but then [use the Payments API with PHP](https://github.com/square/connect-php-sdk#charge-the-card-nonce) to charge card token nonce in place of the Node.js instructions in the walkthrough.

For customer creation, see the PHP SDK docs for [creating a customer](https://github.com/square/connect-php-sdk/blob/master/docs/Api/CustomersApi.md#createcustomer) and the corresponding [CreateCustomer body parameters](https://github.com/square/connect-php-sdk/blob/master/docs/Model/CreateCustomerRequest.md).

**Comment by havenwood** [comment]
Please join us in our [developer community chat](https://squ.re/slack) if you have any other questions!
