### ISSUE TITLE
Release Notes links are all broken

### ISSUE THREAD

**Issue by drbyte** [square/connect-php-sdk#130]
A frequent problem with Square's [Release Notes](https://github.com/square/connect-php-sdk/releases) posts on Github is that none of the associated documentation links actually work.

For example: in https://github.com/square/connect-php-sdk/releases/tag/3.20200422.0 
Here are a few of the links copy-and-pasted just now from the github release notes posted by @lindzeng 30 minutes ago:

https://github.com/square/connect-php-sdk/blob/3.20200422.0/$%7BSQUARE_TECH_REF%7D/devices-api

https://github.com/square/connect-php-sdk/blob/3.20200422.0/customer-groups-api/what-it-does

https://github.com/square/connect-php-sdk/blob/3.20200422.0/webhooks-api/subscribe-to-events

https://github.com/square/connect-php-sdk/blob/3.20200422.0/$%7BSQUARE_TECH_REF%7D/objects/CatalogQuickAmountsSettings

https://github.com/square/connect-php-sdk/blob/3.20200422.0/$%7BSQUARE_TECH_REF%7D/oauth-api/revoke-token#request__property-revoke_only_access_token

**Comment by StephenJosey** [comment]
Thanks for reporting, apologies about the delay. The team is investigating this issue.

**Comment by jessdelacruzsantos** [comment]
The release notes have been retroactively fixed.
