### ISSUE TITLE
Documentation links to model's might be broken

### ISSUE THREAD

**Issue by tristansokol** [square/connect-php-sdk#14]
See:
https://github.com/square/connect-php-sdk/blob/master/docs/Api/TransactionApi.md#charge

the link to Charge Request goes nowhere.

**Comment by frojasg** [comment]
I reported this [issue here](https://github.com/swagger-api/swagger-codegen/issues/5611) and I will try to fix it soon.

**Comment by frojasg** [comment]
This issue was fixed in #19 and #20
