### ISSUE TITLE
Sandbox V2 API Calls - SSL unable to get local issuer certificate

### ISSUE THREAD

**Issue by Jonathan-Garber** [square/connect-php-sdk#30]
I am trying to use Sandbox credentials to work on the V2 API for a project and I always receive an error during testing of any API Calls

`Exception when calling LocationsApi->listLocations: API call to https://connect.squareup.com/v2/locations failed: SSL certificate problem: unable to get local issuer certificate`

Website is hosted on a windows server in IIS and I am using my local hosts file to point my DNS to it as the domain isn't public yet. I have also tested the page directly on the server and still receive the same result.

The content is being loaded across https with a ssl certificate in place. SSL certificate shows it is 100% valid. So what is "unable to get local issuer certificate"

Does the sandbox token not work with the php sdk?

test.php
```
<?php
require_once('square/autoload.php');
// Configure OAuth2 access token for authorization: oauth2
SquareConnect\Configuration::getDefaultConfiguration()->setAccessToken('MySandboxTokenHere');

$api_instance = new SquareConnect\Api\LocationsApi();

try {
    $result = $api_instance->listLocations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling LocationsApi->listLocations: ', $e->getMessage(), PHP_EOL;
}

?>
```

**Comment by Jonathan-Garber** [comment]
Nevermind, I got it. It was related to cURL and verification of the certificate. I had to download a bundle of CA root certs and tell PHP where to find it. This resolved the issue.

**Comment by Jonathan-Garber** [comment]
Also note that to use sandbox credentials with this SDK you must specify the auth headers for it. NOT an OAuth Token.

`SquareConnect\Configuration::getDefaultConfiguration()->addDefaultHeader('Authorization','Bearer MySandboxToken');`

**Comment by tristansokol** [comment]
@Jonathan-Garber That should be done for you automatically, with lines like: https://github.com/square/connect-php-sdk/blob/master/lib/Api/TransactionsApi.php#L150

**Comment by Jonathan-Garber** [comment]
When I first tested that I got the following error.

`Exception when calling LocationsApi->listLocations: [HTTP/1.1 401 Unauthorized] {"errors":[{"category":"AUTHENTICATION_ERROR","code":"UNAUTHORIZED","detail":"This request could not be authorized."}]}`

I just tested again being sure to put the correct token and it did indeed work as expected. Thanks for pointing that out.
