### ISSUE TITLE
v1 model doc links appear to be broken

### ISSUE THREAD

**Issue by tristansokol** [square/connect-php-sdk#34]
See: https://github.com/square/connect-php-sdk/blob/master/docs/Api/V1ItemsApi.md#createitem
Try to click on the link to `\SquareConnect\Model\V1Item` : https://github.com/square/connect-php-sdk/blob/master/docs/Model/v1Item.md correct link is https://github.com/square/connect-php-sdk/blob/master/docs/Model/V1Item.md (notice **V**1item, not v1item). Appears to be a `2.2.0` release bug.

**Comment by bunnyc1986** [comment]
looking
