### ISSUE TITLE
Confusing property naming for catalog "object"

### ISSUE THREAD

**Issue by tristansokol** [square/connect-php-sdk#39]
If you are upserting a catalog object, you would need to create (either implicitly or explicitly) a [UpsertCatalogObjectRequeest](https://github.com/square/connect-php-sdk/blob/master/docs/Model/UpsertCatalogObjectRequest.md). One of those properties is named `object`. That is a tricky because what you actually need to create in PHP world in an associative array, not an object. If it was named "data" or even "body" it might be less confusing. See: [referenced question](https://stackoverflow.com/questions/45745964/using-square-connect-php-sdk-upsertcatalogobject-fatal-error)

**Comment by deanpapastrat** [comment]
Closing for issue cleanup
