### ISSUE TITLE
Missing vendor/autoload.php

### ISSUE THREAD

**Issue by jabcreations** [square/connect-php-sdk#44]
There is no vendor directory provided in this SDK.

**Comment by StephenJosey** [comment]
The vendor directory is created after installing Composer. If you don't use Composer, you will reference the project path directly:
```
require('connect-php-sdk/autoload.php');
```

**Comment by powderblock** [comment]
Does anyone have a copy of v2 autoload.php?

**Comment by StephenJosey** [comment]
@powderblock do you mean the `autoload.php` file for the PHP SDK (discussed above)? If so, you can find it in the root directory of this repo: https://github.com/square/connect-php-sdk/blob/master/autoload.php

Please let me know if I misunderstood, though.
