### ISSUE TITLE
Response from /v2/customers return NULL

### ISSUE THREAD

**Issue by int21ve** [square/connect-php-sdk#48]
```
$result = $api_instance->createCustomer($body);
return $result; //  <== Always NULL 
```

I was diggin into de the code and I think found the problem

`public function createCustomerWithHttpInfo($body)`

` return array(\SquareConnect\ObjectSerializer::deserialize($response, '\SquareConnect\Model\CreateCustomerResponse', $httpHeader), $statusCode, $httpHeader);
`
I think this line is the problem

**Comment by StephenJosey** [comment]
Create Customer works correctly, now. Please let us know if you have issues with it still. Thanks!
