### ISSUE TITLE
listOrders is not listing orders

### ISSUE THREAD

**Issue by mhkhoraidah** [square/connect-php-sdk#54]
I am trying to list orders but it does not list anything. I also when I list transactions, the transaction objects have empty "order Id". I want to display all orders in my site.

**Comment by timtoyoshima** [comment]
Hi, sorry to hear that you are running into some problems with your listOrder call. The listOrder API lists orders from the online store. You can use the Connect V2 listTransactions API to get a list of transactions, get the order IDs, and use batchRetrieveOrders to get the order information you want. Let me know if this is what you need or if you need additional information. Thx Tim

**Comment by timtoyoshima** [comment]
A clarification. The listTransactions API will list only ecommerce transactions (payments). Ecommerce transactions are orders processed through the Connect APIs. The listPayments API will give you an array containing all payments (both your ecommerce and your Square Point of Sale ones). Each payment in the array will contain the items for the order in the itemization field.

**Comment by mhkhoraidah** [comment]
Thanks "timtoyoshima" for your help.
[List Payments](https://github.com/square/connect-php-sdk/blob/master/docs/Api/V1TransactionsApi.md#listpayments) example : listPayments return  array of payment object and each object has items and itemization for that payment or receipt.
