### ISSUE TITLE
Sandbox is not supported for Connect V1 API endpoints

### ISSUE THREAD

**Issue by ozlemdemirci** [square/connect-php-sdk#58]
Hello,

I would like to implement a categorization to our integration. However, you don't allow Sandbox mode.

How can I develop categorization without testing? Please help.

Thank you.

**Comment by StephenJosey** [comment]
Currently the only way to test V1 API endpoints is to use production credentials, unfortunately. You can take payments in sandbox mode, though, so you should be able to successfully developer your categorization. Please let me know if you have further questions or concerns.

**Comment by Coding0998888** [comment]
I am trying to implement payment notification webhook through PHP CURL, but i am getting "Sandbox is not supported for Connect V1 API endpoints" error. I want to test payment notification in sandbox before we can move to production. Please help me on this.  Here is a link to my question on stackoverflow https://stackoverflow.com/questions/53261799/how-to-check-webhook-in-sandbox-for-squareup-payment-gateway

**Comment by StephenJosey** [comment]
Hi @Coding0998888, unfortunately Sandbox is not currently supported on any V1 endpoints. You'll need to use your production credentials to test them. However, you can do a cash payment on Square's POS application, which will trigger a webhook notification, and obviously not charge you. (You can also refund the cash transaction if you're trying to keep proper bookkeeping.)

**Comment by Coding0998888** [comment]
@StephenJosey Actually we are using a simple web form to collect payment from our users. So i don't know about Square POS.

**Comment by StephenJosey** [comment]
@Coding0998888 That's fine, I was just letting you know how you could "test" the webhooks. It will only work with production credentials, so you'll need to enable it using your production credentials. If you don't want to use the POS app, you can just take a $1.00 charge on the Square payment form, and then refund yourself afterward, to test the webhook notification.
