### ISSUE TITLE
Prototype Error: MissingInputTypeError: The SqPaymentForm `function(c) {...}` option is required.

### ISSUE THREAD

**Issue by jabcreations** [square/connect-php-sdk#74]
Greetings. I've begun integrating the Square form directly on to pages since it appears that the forms are working when the page is served as XML (application/xhtml+xml).

However I encountered a strange error; the JAB Creations web platform uses the following prototypes:

```
Object.prototype.class_ = function(c)
{
 return (this.getElementsByClassName && this.getElementsByClassName(c) && this.getElementsByClassName(c).length > 0) ? this.getElementsByClassName(c) : false;
}

Object.prototype.tag_ = function(t)
{
 return (this.getElementsByTagName && this.getElementsByTagName(t) && this.getElementsByTagName(t).length > 0) ? this.getElementsByTagName(t) : false;
}
```

This triggers the following error:

> MissingInputTypeError: The SqPaymentForm `function(c)
> {
>  return (this.getElementsByClassName && this.getElementsByClassName(c) && this.getElementsByClassName(c).length > 0) ? this.getElementsByClassName(c) : false;
> }` option is required.
> See: https://docs.connect.squareup.com/api/paymentform#configurationfields

I could comment out my own prototypes though I shouldn't have to. A fix would be greatly appreciated.

**Comment by StephenJosey** [comment]
Currently the Square Payment Form doesn't support `Object.prototype` being modified, and typically it's frowned upon modifying `Object.prototype` as it could cause issues across libraries. I strongly encourage you to not modify the `Object.prototype` to prevent future problems.

I'll pass this feedback along to the appropriate team, though, and let you know if anything changes. We're always working to improve compatibility, so we definitely appreciate these issues being brought forth so we can create the best experience for everyone.
