### ISSUE TITLE
how to add poastcal code into nonce

### ISSUE THREAD

**Issue by ipehimanshu** [square/connect-php-sdk#93]
i got error like 
Postal code is required for nonces used by merchants in `IN` and i want to add postal code by manually using php api .

Can you please help us ?

Thanks

**Comment by deanpapastrat** [comment]
Hey @ipehimanshu, to add the postal code for nonce generation, you'll need to do it in the In-App Payments SDK or Square Payment Form; it cannot be added with one of the backend Connect APIs.

I'm closing this, feel free to reopen if you need further info.
