### ISSUE TITLE
INTERNAL_SERVER_ERROR comes when use production mode and product details to save card info

### ISSUE THREAD

**Issue by ipehimanshu** [square/connect-php-sdk#99]
[HTTP/1.1 500 Internal Server Error] {"errors":[{"category":"API_ERROR","code":"INTERNAL_SERVER_ERROR","detail":"An internal error has occurred, and the API was unable to service your request."}]}

**Comment by ipehimanshu** [comment]
i see now this type error when creating customer and save card for customer
[HTTP/2 503] upstream connect error or disconnect/reset before headers. reset reason: overflow 503

**Comment by okenshields** [comment]
@ipehimanshu , that particular error was caused by a blip yesterday. Do you see that error now?

**Comment by ipehimanshu** [comment]
blip means ?
i am not getting ?

**Comment by sseaman** [comment]
Was an issue on our side.  Resolved.
